version: "3"
services:
  build: &build
    image: mpppk/gored
    volumes:
      - $PWD:/go/src/github.com/mpppk/goreleng-test
    environment:
      GITHUB_TOKEN: $GITHUB_TOKEN
      REPO_OWNER: mpppk
    working_dir: /go/src/github.com/mpppk/goreleng-test
    command: gored build
  build-docker:
    <<: *build
    command: gored build-docker
  release:
    <<: *build
#    command: gored release
    command: sh /scripts/release.sh
