version: 2
jobs:
  build:
    docker:
      - image: mpppk/gored
    working_directory: /go/src/github.com/mpppk/goreleng-test
    steps:
      - checkout
      - run: make test
  release:
    docker:
      - image: mpppk/gored
    working_directory: /go/src/github.com/mpppk/goreleng-test
    steps:
      - checkout
      - run: make release
workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
